import type { Metadata } from "next";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { auth, currentUser } from "@clerk/nextjs/server";
import { db } from "@/lib/db";
import Headers from "./components/Headers";
import Footer from "./components/Footer";
import ProfileForm from "./components/ProfileForm";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  //Clerk user id
  const { userId } = auth();
  // console.log(userId);

  //Clerk info for user
  const user = await currentUser();

  //SELECT profile for user
  const result = await db.query(
    `SELECT * FROM users2 WHERE clerk_id = '${userId}'`
  );

  // console.log(result);

  //UPDATE profile pic if user exists
  if (userId && result.profile_pic == null)
    await db.query(
      `UPDATE users2 SET profile_picture = '${user.imageUrl}' WHERE clerk_id = '${userId}'`
    );

  //INSERT new user if user doesn't exist
  if (result.rowCount === 0 && userId !== null) {
    await db.query(`INSERT INTO users2 (clerk_id) VALUES ('${userId}')`);
  }

  //If user, show page, else show form
  const hasUsername = result.rows[0]?.username != null ? true : false;

  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <Headers />
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <main>
            <SignedOut>{children}</SignedOut>

            {hasUsername && children}
            {!hasUsername && <ProfileForm />}
          </main>
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
